### ISSUE TITLE
Memory Leak?  Is there a way to release resources?

### ISSUE THREAD

**Issue by seanadkinson** [googlesamples/cardboard-ios#16]
Our app let's you open 360 videos, watch them for a certain amount of time, and then it sends you back to the video selection page.  After opening 6-7 videos, the app crashes with memory warnings.  Is there any chance this library is holding on to resources too long?  Is there a way to explicitly clean up?

Any guidance is certainly appreciated.  If this is the wrong repo to put issues with the SDK please let me know.  And also please open source soon, as I'd love to fix issues and put up PRs.

Thanks.

**Comment by seanadkinson** [comment]
I had been creating new `GCSVideoView`s each time I was playing a video, but I've since switched to just having a single `GCSVideoView` that I keep around, and just play different videos with.  That has resolved the issue with my app's memory climbing forever.  I have some traces saved that show the `malloc`s that were created at each generation, but I'm not too confident in my ability to read the traces correctly, so I'll save the details, unless you'd like me to elaborate more.  I'll close for now, but can help diagnose if needed.

**Comment by myflashlab** [comment]
Great idea :) I just did what you suggested and my app won't leak memory any more. Thank you. I should have read your ticket before posting this one though! https://github.com/googlevr/gvr-ios-sdk/issues/33

Anyway, I feel like I'll be leaving that ticket open because what we managed to bypass here is not clean enough! I'll be happy to have this problem fixed in future versions of GVR.

**Comment by Anchlate** [comment]
Hello , I have the same problem , but  i do not how to resolve it , can you help me? thanks
